---
name: ci
on:
  push:
    branches:
      - main
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    strategy:
      matrix:
        otp:
          - 25
          - 26
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - run: make all dialyze eunit
  site:
    needs: build
    strategy:
      matrix:
        otp:
          - 26
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - run: make tests edoc
      - run: curl --proto '=https' --tlsv1.2 -sSf https://shortishly.github.io/coverdata/coverdata | escript coverdata --input cover/eunit.coverdata --output _site/coverage.json 
      - uses: actions/upload-pages-artifact@v1
        with:
          path: _site
  deploy:
    needs: site
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
